FROM ubuntu:26.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
      build-essential \
      debhelper \
      cmake \
      g++ \
      qt6-base-dev \
      qt6-svg-dev \
      libqt6sql6-sqlite \
      zlib1g-dev \
      librsvg2-bin \
      desktop-file-utils \
      appstream \
      lintian \
      fakeroot \
      ca-certificates \
 && rm -rf /var/lib/apt/lists/*
